plugins {
	id 'java-library'
	id 'net.minecraftforge.gradle' version '6.0.+'
	id 'idea'
	id 'maven-publish'
}

idea {
	module {
		inheritOutputDirs = true
		excludeDirs += file('./minecraft')
	}
}

java {
	toolchain.languageVersion = JavaLanguageVersion.of(8)
	sourceCompatibility = targetCompatibility = JavaVersion.VERSION_1_8
}

legacy {
	fixClasspath = true
	extractMappings = true
	attachMappings = true
}

repositories {
	mavenCentral()
	maven {
		// Su5ed LegacyDev Fork
		url = "https://maven.su5ed.dev/releases"
	}
}

minecraft {
	mappings channel: 'stable', version: '39-1.12'
	// accessTransformer = file('src/main/resources/META-INF/modid_at.cfg')

	runs {
		configureEach {
			workingDirectory file('minecraft')

			property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
			property 'forge.logging.console.level', 'debug'
			environment 'MC_VERSION', '1.12.2'

			mods {
				"${mod_id}" {
					source sourceSets.main
				}
			}
		}

		client {}
	}
}

dependencies {
	minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'

	constraints {
		implementation('net.minecraftforge:legacydev:0.3.0.0-legacyExt') {
			because 'needed to have all ATs work properly'
		}

		implementation('org.ow2.asm:asm-debug-all:5.2') {
			because 'newer ASM versions include module info that causes errors in Java 8'
		}
	}

	configurations.forEach {
		// MergeTool pollutes the classpath with conflicting classes
		it.exclude(group: 'net.minecraftforge', module: 'mergetool')

		// LegacyDev forge dep wants fatjar as the classifier, but 3.0 lacks it
		it.resolutionStrategy.eachDependency {
			if (it.requested.module.toString() == "net.minecraftforge:legacydev") {
				it.artifactSelection {
					it.selectArtifact(DependencyArtifact.DEFAULT_TYPE, null, null)
				}
			}
		}
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

jar {
	manifest {
		attributes 'FMLCorePlugin': 'com.gamerforea.fontfix.LoadingPlugin'
		attributes 'FMLCorePluginContainsFMLMod': 'true'
	}
}

tasks.register('devJar', Jar) {
	archiveClassifier.set('dev')
	manifest = jar.manifest
	from sourceSets.main.output
}

artifacts {
	archives tasks.named('devJar')
}
